import './globals.css'
import NextTopLoader from 'nextjs-toploader';
import Navbar from '@/components/Navbar'

export const metadata= {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <NextTopLoader color="#269669" height={3} showSpinner={true} speed={200}/>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
